stages:
  - build
  - alt-build
  - publish

variables:
  DOCKER_REGISTRY: registery.duniter.org
  IMAGE_NAME: geconomicus_ci

fast-build:
  stage: build
  image: $DOCKER_REGISTRY/$IMAGE_NAME
  script:
    #- ./update_translation.sh
    - ./build.sh
    - mv ./rst/build/html public
    - ./build_en_US.sh
    - mv ./rst/build/html public/en
  after_script:
    - cat /tmp/sphinx-err-*.log || true
  artifacts:
    paths:
      - public
    expire_in: 10 minutes
  only:
    - master

failsafe-long-build:
  stage: alt-build
  when: on_failure
  image: python:3.4
  before_script:
    - apt-get update
    - apt-get install -y zip inkscape imagemagick
    - pip install sphinx==1.3
    - pip install sphinx-intl
    - pip install docutils==0.12
    #- identify -list font || true
  script:
    #- ./update_translation.sh
    - ./build.sh
    - mv ./rst/build/html public
    - ./build_en_US.sh
    - mv ./rst/build/html public/en
  after_script:
    - cat /tmp/sphinx-err-*.log || true
  artifacts:
    paths:
      - public
    expire_in: 10 minutes
  only:
    - master

docker-for-fast-build:
  stage: alt-build
  when: on_failure
  allow_failure: true
  variables:
    GIT_STRATEGY: none
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo 'FROM python:3.4' > Dockerfile
    - echo 'RUN apt-get update && apt-get install -y zip inkscape imagemagick' >> Dockerfile
    - echo 'RUN pip install sphinx==1.3 sphinx-intl docutils==0.12' >> Dockerfile
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build --pull -t ${DOCKER_REGISTRY}/${IMAGE_NAME} .
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

pages:
  stage: publish
  when: always
  script:
    - ls public
  artifacts:
    paths:
      - public
  only:
    - master

mirror:
  stage: publish
  when: always
  image: liaohuqiu/rsync
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - >-
      [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >
      ~/.ssh/config
  script:
    - rsync -az -e ssh ./public/ gammanu@1000i100.fr:~/geconomicus
  only:
    - master
